"""
Person 1: Central JSON Data Contract & Pydantic Schema
Used across all modules (Person 1, 2, 3, 4) to ensure strictly typed interoperability.
"""
from datetime import datetime
from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field


class RiskLevel(str, Enum):
    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"


class HazardCategory(str, Enum):
    CHEMICAL_TOXIC = "Chemical / Toxic Hazard"
    MECHANICAL_CRUSH = "Mechanical / Pinch / Struck-by"
    ELECTRICAL = "Electrical / Arc Flash"
    SLIP_TRIP_FALL = "Slip / Trip / Surface Hazard"
    FALLING_OBJECTS_HEIGHT = "Working at Height / Falling Objects"
    THERMAL_FIRE = "Thermal / Fire / Hot Work"
    ATMOSPHERIC_CONFINED = "Atmospheric / Confined Space"
    ERGONOMIC_PHYSIOLOGICAL = "Ergonomic / Heavy Lifting"
    PROCESS_SAFETY = "Process Safety / Pressure Excursion"


class NearMissReport(BaseModel):
    """Raw Near-Miss Ingestion Model."""
    id: str = Field(description="Unique report identifier, e.g. 'NM-2024-001'")
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"))
    facility: str = Field(..., description="Facility name or manufacturing complex")
    department: str = Field(..., description="Department or operating sector")
    location_specific: str = Field(..., description="Exact zone, e.g., 'Bay 4, Chemical Transfer Deck'")
    reporter_role: str = Field(default="Frontline Operator", description="Role of the person reporting")
    raw_text: str = Field(..., description="Free-text narrative of the near miss / safety observation")
    equipment_involved: Optional[str] = Field(default="N/A", description="Equipment, machinery, or tools involved")
    environmental_factors: Optional[str] = Field(default="Normal", description="Lighting, floor condition, weather")
    immediate_action_taken: Optional[str] = Field(default="None logged", description="Corrective measure applied immediately")


class StructuredExtraction(BaseModel):
    """Structured extraction parsed by Person 2 LLM/Agent from free-text."""
    report_id: str
    primary_hazard: str = Field(..., description="Primary identified hazard")
    hazard_category: HazardCategory = Field(default=HazardCategory.SLIP_TRIP_FALL)
    precursor_events: List[str] = Field(
        default_factory=list,
        description="Early warning signals and immediate unsafe acts/conditions"
    )
    affected_assets: List[str] = Field(
        default_factory=list,
        description="Workers, contractors, equipment, or environment at risk"
    )
    failed_safeguards: List[str] = Field(
        default_factory=list,
        description="Defeated guards, missing PPE, procedural omissions, or worn interlocks"
    )
    recommended_mitigation: str = Field(..., description="Immediate engineering or administrative control")


class RiskAssessment(BaseModel):
    """Risk scoring and precursor analysis generated by Person 2."""
    report_id: str
    risk_level: RiskLevel = Field(..., description="Classified risk level: Low, Medium, High")
    risk_score: float = Field(ge=0.0, le=10.0, description="Quantitative hazard score from 0.0 to 10.0")
    confidence: float = Field(ge=0.0, le=1.0, default=0.92, description="Confidence in classification")
    rationale: str = Field(..., description="Technical justification for assigned risk level")
    osha_citations: List[str] = Field(
        default_factory=list,
        description="Relevant OSHA standards or industrial safety benchmarks (e.g. 1910.22, 1910.1200)"
    )
    precursor_severity_signals: List[str] = Field(
        default_factory=list,
        description="Critical precursor tags indicating escalation potential (e.g., 'Fatal Precursor', 'Pinch Point')"
    )
    escalation_potential: bool = Field(
        default=False,
        description="True if an unaddressed precursor could lead to a Lost Time Incident (LTI) or fatality"
    )


class RiskOverride(BaseModel):
    """Compulsory Add-on: Human-in-the-loop override logged with justification."""
    id: Optional[str] = None
    report_id: str
    original_risk: RiskLevel
    overridden_risk: RiskLevel
    safety_officer_id: str = Field(default="SO-Officer-1")
    override_reason: str = Field(
        ...,
        min_length=5,
        description="Safety Officer rationale explaining why the risk level was adjusted"
    )
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"))


class EnrichedReport(BaseModel):
    """Complete consolidated representation uniting raw data, extraction, risk score, and human overrides."""
    report: NearMissReport
    extraction: StructuredExtraction
    assessment: RiskAssessment
    overrides: List[RiskOverride] = Field(default_factory=list)
    effective_risk_level: RiskLevel = Field(default=RiskLevel.MEDIUM)
